version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    networks:
      - ribbit-network

  ribbitreels-api:
    build:
      context: .
      dockerfile: RibbitReels.Api/Dockerfile
    container_name: ribbitreels-api
    ports:
      - "8080:80"
    env_file:
      - ./RibbitReels.Api/.env
    environment:
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://0.0.0.0:80"
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=RibbitReelsDb;User Id=sa;Password=Password123!;TrustServerCertificate=True"
    depends_on:
      - sqlserver
    networks:
      - ribbit-network

networks:
  ribbit-network:
    driver: bridge
