name: CI - Build, Migrate, and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: Password123!
          ACCEPT_EULA: Y
        ports:
          - 1433:1433
        options: >-
          --health-cmd "echo 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    env:
      GITHUB_ACTIONS: true
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=RibbitReelsDb;User Id=sa;Password=Password123!;TrustServerCertificate=True
      Jwt__Key: ${{ secrets.JWT__KEY }}
      Jwt__Issuer: ${{ secrets.JWT__ISSUER }}
      Jwt__Audience: ${{ secrets.JWT__AUDIENCE }}
      Jwt__ExpireMinutes: ${{ secrets.JWT__EXPIREMINUTES }}
      GoogleAuth__ClientId: ${{ secrets.GOOGLEAUTH__CLIENTID }}
      GoogleAuth__ClientSecret: ${{ secrets.GOOGLEAUTH__CLIENTSECRET }}
      Authentication__TestUser__UserId: ${{ secrets.AUTHENTICATION__TESTUSER__USERID }}
      Authentication__TestUser__Email: ${{ secrets.AUTHENTICATION__TESTUSER__EMAIL }}
      Authentication__TestUser__Name: ${{ secrets.AUTHENTICATION__TESTUSER__NAME }}
      Authentication__TestUser__Role: ${{ secrets.AUTHENTICATION__TESTUSER__ROLE }}

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 📦 Restore NuGet dependencies
        run: dotnet restore

      - name: 🛠️ Build solution
        run: dotnet build --no-restore --configuration Release

      - name: 🧰 Restore EF Core CLI Tool
        run: dotnet tool restore

      - name: 🕒 Wait for SQL Server to be ready
        run: |
          for i in {1..30}; do
            nc -z sqlserver 1433 && echo "✅ SQL Server is ready!" && break
            echo "⏳ Waiting for SQL Server on port 1433... ($i)"
            sleep 5
          done

      - name: 🧬 Run EF Core Migrations
        run: dotnet tool run dotnet-ef database update --project ./RibbitReels.Data --startup-project ./RibbitReels.Api
        env:
          DOTNET_ENVIRONMENT: Development

      - name: ✅ Run Unit and Integration Tests
        run: dotnet test --no-build --configuration Release
        env:
          DOTNET_ENVIRONMENT: Development
